### ISSUE TITLE
data of skel folder under user

### ISSUE THREAD

**Issue by ayushikhandelwal99** [kshitizsaini113/reboot-2.0#1]
we have to only copy the subdirectories of skel folder but you are copying the folder whole

**Comment by ayushikhandelwal99** [comment]
use cp -a instead 
and if you don't use verbose you don't need to redirect the output to null

**Comment by kshitizsaini113** [comment]
@ayushikhandelwal99 thanks, can you comment the corrected line, will update it

**Comment by ayushikhandelwal99** [comment]
sure
cp -a /etc/skel/. /home/$uname/

**Comment by kshitizsaini113** [comment]
Feel free to generate a pull requst. It will be great to work collaboratively
